name: InTheWild
version: 0.5.1
api-version: 1.16
main: io.Github.PancakeBoiii.InTheWild.Main
author: PancakeBoiii
depend: [PancakeCore]
commands:
  reload:
    description: Reloads the config!
  setthirst:
    description: Sets the thirst of a player
  settemp:
    description: Sets the temperature of a player